local utils = require ('pl.utils')
local test = require('pl.test')
local asserteq = test.asserteq

asserteq(utils.to_bool("y"), true)
asserteq(utils.to_bool("y", nil), true)
asserteq(utils.to_bool("y", {}, true), true)
asserteq(utils.to_bool("yes"), true)
asserteq(utils.to_bool("yes"), true)
asserteq(utils.to_bool("t"), true)
asserteq(utils.to_bool("true"), true)
asserteq(utils.to_bool("1"), true)
asserteq(utils.to_bool("a"), false)
asserteq(utils.to_bool("a", {"a"}), true)
asserteq(utils.to_bool("a", {"b"}), false)
asserteq(utils.to_bool(1), true)
asserteq(utils.to_bool(10), true)
asserteq(utils.to_bool(100), true)
asserteq(utils.to_bool(0), false)
asserteq(utils.to_bool(true), true)
asserteq(utils.to_bool(false), false)
asserteq(utils.to_bool({}), false)
asserteq(utils.to_bool({}, nil, true), false)
asserteq(utils.to_bool({"a"}), false)
asserteq(utils.to_bool({"a"}, nil, false), false)
asserteq(utils.to_bool({"a"}, nil, true), true)
asserteq(utils.to_bool(print), false)
asserteq(utils.to_bool(print, nil, true), true)
asserteq(utils.to_bool(print, {}, true), true)
asserteq(utils.to_bool(print, {}, false), false)
